name: Commit Regularly

permissions:
  contents: write

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run at 20:02 UTC
  schedule:
   - cron: '7 16,17,18,19,20,21,22,23 * * *'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3

      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > time.txt

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "NoahAppelbaum"
          git config user.email "noahappelbaum@gmail.com"
      
      - name: commit conditionally
        run: |
          # Stage the file, commit and push, conditionally
          if $(($RANDOM % 2)); then
            git add time.txt
            git commit -m "Updated time file `date`"
            git push origin main
          fi
